# Profile
spring.profiles.active=${PROFILE}

# Locale
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# Version
info.app.version=@project.version@

# Springdoc OpenApi 3.1 Swagger 3
springdoc.api-docs.path=/docs-medfacil
springdoc.swagger-ui.path=/docs-medfacil.html

# Server
server.error.include-stacktrace=never
server.servlet.context-path=/medfacil-api
server.port=${PORT}

